import * as Scrivito from "scrivito";
import { random32CharHex } from "./random32CharHex";

Scrivito.provideEditingConfig("FormContainerWidget", {
  title: "Form",
  attributes: {
    formId: {
      title: "Form ID",
      description: "Autogenerated - please do not modify",
    },
  },
  initialContent: {
    formId: () => random32CharHex(),
  },
  properties: ["formId"],
});
